package com.wso2telco.util;

public enum UserState {

    INACTIVE,ACTIVE,
    OFFLINE_OPERATOR_MOVE_OUT,
    OFFLINE_OPERATOR_MOVE_IN,
    OFFLINE_INVALID_OPERATOR,
    OFFLINE_OPERATOR_VERIFICATION_FAILED,
    OFFLINE_USER_REGISTRATION_FAILED,
    OFFLINE_USER_REGISTRATION,
    OFFLINE_USER_UNREGISTRATION_SUCCESS,
    OFFLINE_USER_UNREGISTRATION_FAILED_;


}
